export const SET_USER = 'SET_USER';
export const SET_FILTER = 'SET_FILTER';
export const FETCH_ADVERTS_REQUEST = 'FETCH_ADVERTS_REQUEST';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILUER';